[package]
name = "rl1"
version = "0.1.0"
edition = "2021"

[dependencies.gridbugs]
version = "0.2"
features = [
    "chargrid_wgpu",
    "chargrid_ansi_terminal",
    "chargrid",
    "backend",
]

[dependencies]
meap = "0.5"
